# Generated by Django 4.2.1 on 2023-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Enter the full name of client.')),
                ('phone', models.CharField(max_length=13, verbose_name='Enter the phone number of client.')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
