# Generated by Django 4.2.1 on 2023-05-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255)),
                ('photo', models.FileField(blank=True, null=True, upload_to='product/category_images', verbose_name='Category photo')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Feature',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.country', verbose_name='Developed')),
            ],
            options={
                'verbose_name': 'Manufacturing plant',
                'verbose_name_plural': 'Manufacturing plants',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sale_count', models.IntegerField(default=0, verbose_name='Count of sales')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='Number of views')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.country', verbose_name='Country of origin')),
                ('manufactory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufactory_re', to='product.manufactory', verbose_name='Manufactory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=255, verbose_name='Unit of measure')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Product price',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='product/product_images', verbose_name='Video/Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_media', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Product Videos/Photos',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.character', verbose_name='Product feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_character', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Product feature',
            },
        ),
    ]
