# Generated by Django 4.2.1 on 2023-05-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0001_initial'),
        ('provider', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Cost name')),
            ],
        ),
        migrations.CreateModel(
            name='OutlayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Outlay category')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'наличные'), ('card', 'карта'), ('bank', 'банк')], max_length=255, verbose_name='Payment method')),
                ('payment_type', models.CharField(choices=[('income', 'доход'), ('order', 'заказ'), ('client', 'клиент'), ('provider', 'провайдер'), ('outlay', 'расход')], max_length=255, verbose_name='Payment type')),
                ('transaction_type', models.CharField(choices=[('income', 'доход'), ('outcome', 'расход')], max_length=50, verbose_name='Transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Value')),
                ('is_deleted', models.BooleanField(verbose_name='Deleted')),
                ('comment', models.CharField(max_length=400, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Deleted date')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by the employee')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_user', to=settings.AUTH_USER_MODEL, verbose_name='Deleted employee')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='income.income', verbose_name='Product income')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Order')),
                ('outlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.outlay', verbose_name='Outlay name')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='provider.provider', verbose_name='Provider')),
            ],
        ),
        migrations.AddField(
            model_name='outlay',
            name='outlay_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.outlaycategory', verbose_name='Outlay category'),
        ),
    ]
