# Generated by Django 4.2.1 on 2023-05-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('total', models.DecimalField(decimal_places=2, max_digits=17, null=True, verbose_name='Total')),
                ('self_price', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Self price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Product name')),
            ],
            options={
                'verbose_name': 'Warehouse product',
                'verbose_name_plural': 'Warehouse products',
            },
        ),
    ]
