# Generated by Django 4.2.1 on 2023-05-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'созданный'), ('accepted', 'потверждённый'), ('completed', 'завершённый'), ('canceled', 'отклонённый')], max_length=255, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Base name')),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('total', models.DecimalField(decimal_places=2, max_digits=17, null=True, verbose_name='Amount')),
                ('self_price', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='The actual price of the product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Product name')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Base')),
            ],
            options={
                'verbose_name': 'Base product',
                'verbose_name_plural': 'Base products',
            },
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Product count')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.movement', verbose_name='Excerpt')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_warehouse', to='warehouse.warehouse', verbose_name='From warehouse'),
        ),
        migrations.AddField(
            model_name='movement',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_warehouse', to='warehouse.warehouse', verbose_name='To warehouse'),
        ),
    ]
