# Generated by Django 4.2.1 on 2023-05-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('completed', 'Complated'), ('canceled', 'Canceled')], default='created', max_length=255, verbose_name='Prodcut status')),
                ('total', models.DecimalField(decimal_places=2, max_digits=17, null=True, verbose_name='Price')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Price')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('total', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Order')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
    ]
